# Generated by Django 5.0.7 on 2024-07-26 16:52

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef12345', length=5, max_length=10, prefix='', unique=True)),
                ('titulo', models.CharField(default='Titulo', max_length=50)),
                ('imagem', models.ImageField(upload_to='produto')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_status', models.CharField(choices=[('rascunho', 'Rascunho'), ('desabilitado', 'Desabilitado'), ('publicado', 'Publicado')], max_length=12)),
                ('en_estoque', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja_online.categoria')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
